/**
 * Render site/privacy.html from extension/PRIVACY.md.
 *
 * The store listing points at the published page while the extension ships the
 * markdown, so two copies of the same promise exist and only one of them is the
 * one a regulator would read. Deriving the page removes the possibility that
 * they disagree.
 *
 * The previous page was produced by something that no longer exists, and it
 * showed: every source line became its own paragraph, so sentences broke in the
 * middle of themselves. Markdown wraps for the author's benefit and a renderer
 * has to undo that, which is most of what this file does.
 *
 * Run: node tools/build-privacy.mjs
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(root, 'extension', 'PRIVACY.md');
const OUT = join(root, 'site', 'privacy.html');

const escape = (s) => s
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/** Bold and inline code only. The policy uses nothing else, and a renderer that
 *  supports more than its input needs is a source of surprises, not features. */
const inline = (s) => escape(s)
  .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
  .replace(/`([^`]+)`/g, '<code>$1</code>');

const cells = (line) => line.slice(1, -1).split('|').map((c) => c.trim());

/** @param {string} md @returns {string} */
export function render(md) {
  const lines = md.replace(/\r\n/g, '\n').split('\n');
  const out = [];
  let para = [];
  let list = null;

  // A paragraph ends at a blank line or a block element, not at a newline.
  const flushPara = () => {
    if (para.length) out.push(`<p>${inline(para.join(' '))}</p>`);
    para = [];
  };
  const flushList = () => {
    if (list) out.push(`<ul>\n${list.map((i) => `<li>${inline(i)}</li>`).join('\n')}\n</ul>`);
    list = null;
  };
  const flush = () => { flushPara(); flushList(); };

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();

    if (!trimmed) { flush(); continue; }

    const heading = /^(#{1,4})\s+(.*)$/.exec(trimmed);
    if (heading) {
      flush();
      const level = heading[1].length;
      out.push(`<h${level}>${inline(heading[2])}</h${level}>`);
      continue;
    }

    // A table is its header row, an alignment row, then body rows.
    if (trimmed.startsWith('|') && /^\|[\s:|-]+\|$/.test(lines[i + 1]?.trim() ?? '')) {
      flush();
      const head = cells(trimmed);
      const body = [];
      i += 2;
      while (i < lines.length && lines[i].trim().startsWith('|')) {
        body.push(cells(lines[i].trim()));
        i++;
      }
      i--;
      out.push(
        '<table><thead><tr>'
        + head.map((c) => `<th>${inline(c)}</th>`).join('')
        + '</tr></thead><tbody>\n'
        + body.map((r) => `<tr>${r.map((c) => `<td>${inline(c)}</td>`).join('')}</tr>`).join('\n')
        + '\n</tbody></table>',
      );
      continue;
    }

    const item = /^[-*]\s+(.*)$/.exec(trimmed);
    if (item) {
      flushPara();
      list = list ?? [];
      list.push(item[1]);
      continue;
    }

    // An indented line under a list item continues it rather than starting a
    // paragraph. Without this, every wrapped bullet became its own stray line.
    if (list && /^\s+\S/.test(line)) {
      list[list.length - 1] += ` ${trimmed}`;
      continue;
    }

    flushList();
    para.push(trimmed);
  }
  flush();

  const title = /^#\s+(.*)$/m.exec(md)?.[1] ?? 'Privacy policy';

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escape(title)}</title>
<link rel="icon" href="assets/icon-128.png">
<link rel="stylesheet" href="style.css">
<style>
  main { max-width: 42em; margin: 0 auto; padding: 48px 0 80px; }
  main h1 { font-size: 2rem; }
  main table { border-collapse: collapse; width: 100%; margin: 16px 0; }
  main th, main td { text-align: left; padding: 8px 12px; border-bottom: 1px solid var(--line); vertical-align: top; }
  main th { font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.04em; color: var(--muted); }
  main li { margin: 6px 0; }
</style>
</head>
<body>
<!-- Generated by tools/build-privacy.mjs from extension/PRIVACY.md. Do not edit by hand. -->
<main>
${out.join('\n')}
</main>
</body>
</html>
`;
}

// Importable for tests, runnable as a script.
if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) {
  writeFileSync(OUT, render(readFileSync(SRC, 'utf8')));
  console.log(`wrote ${OUT}`);
}
